# Generated by Django 5.2.4 on 2025-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_apicalllog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airtraffic',
            name='aircraft_type',
        ),
        migrations.RemoveField(
            model_name='airtraffic',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='airtraffic',
            name='callsign',
        ),
        migrations.RemoveField(
            model_name='airtraffic',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='airtraffic',
            name='estimated_arrival',
        ),
        migrations.RemoveField(
            model_name='airtraffic',
            name='flight_id',
        ),
        migrations.RemoveField(
            model_name='airtraffic',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='airtraffic',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='airtraffic',
            name='origin_country',
        ),
        migrations.RemoveField(
            model_name='airtraffic',
            name='velocity',
        ),
        migrations.RemoveField(
            model_name='satellitetraffic',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='satellitetraffic',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='satellitetraffic',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='satellitetraffic',
            name='mission_type',
        ),
        migrations.RemoveField(
            model_name='satellitetraffic',
            name='norad_id',
        ),
        migrations.RemoveField(
            model_name='satellitetraffic',
            name='operational_status',
        ),
        migrations.RemoveField(
            model_name='satellitetraffic',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='satellitetraffic',
            name='satellite_name',
        ),
        migrations.RemoveField(
            model_name='satellitetraffic',
            name='velocity',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='cloud_percentage',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='precipitation',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='uv_index',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='weather_description',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='wind_speed',
        ),
        migrations.AddField(
            model_name='airtraffic',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satellitetraffic',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='prediction_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='weather_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apicalllog',
            name='query_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apicalllog',
            name='response_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PredictionResult',
        ),
    ]
