# Generated by Django 5.2.4 on 2025-08-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_remove_airtraffic_aircraft_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airtraffic',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='satellitetraffic',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='prediction_result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
