# Generated by Django 5.2.4 on 2025-09-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_airtraffic_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SatelliteTraffic',
        ),
    ]
